# curl -X GET http://localhost:8888/needToken -H "token:12345"
GET http://localhost:8888/needToken
token: 12345

###

# curl -X GET http://localhost;8888/needToken -H token=123
GET http://localhost:8888/needToken
token=123:

###

GET http://localhost:8888/noneedToken


###
GET http://localhost:8888/needToken
